services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - devstagram-app
        depends_on:
            - mysql
            # - redis
            # - meilisearch
            # - mailpit
            # - selenium
        restart: unless-stopped
    # Base de datos MySQL
    mysql:
        image: 'mysql:9'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes:
            - 'mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - devstagram-app
        restart: unless-stopped

    # Caché y sistema de colas  Redis
    # redis:
    #     image: 'redis:alpine'
    #     # ports:
    #     #     - '${FORWARD_REDIS_PORT:-6379}:6379'
    #     volumes:
    #         - 'redis:/data'
    #     networks:
    #         - devstagram-app
    #     restart: unless-stopped

    # # Motor de búsqueda Meilisearch
    # meilisearch:
    #     image: 'getmeili/meilisearch:latest'
    #     environment:
    #         MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    #     volumes:
    #         - 'meilisearch:/meili_data'
    #     networks:
    #         - devstagram-app
    #     restart: unless-stopped

    # # Servidor de correo Mailpit
    # mailpit:
    #     image: 'axllent/mailpit:latest'
    #     # ports:
    #     #     - '${FORWARD_MAILPIT_PORT:-1025}:1025'
    #     #     - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    #     networks:
    #         - devstagram-app
    #     restart: unless-stopped

    # # Servidor de Selenium para pruebas de navegador
    # selenium:
    #     image: selenium/standalone-chromium
    #     extra_hosts:
    #         - 'host.docker.internal:host-gateway'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - devstagram-app
    #     restart: unless-stopped
networks:
    devstagram-app:
        driver: bridge
volumes:
    mysql:
        driver: local
    # redis:
    #     driver: local
    # meilisearch:
    #     driver: local
